version: "3.8"

services:
  b-actix:
    build:
      context: ./
      dockerfile: ./services/nginx/Dockerfile

  f-main:
    build:
      context: ./services/f-main
      dockerfile: ./services/f-main/Dockerfile.deploy
    container_name: f-core
    volumes:
      - ./services/f-core:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - b-core
    networks:
      - default

networks:
  default:
    driver: bridge
