version: "3.8"

services:
  ui-core:
    stdin_open: true
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    container_name: ui
    volumes:
      - ./services/ui:/app/ui
      - /app/ui/node_modules
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_API_SERVICE_URL=${REACT_APP_API_SERVICE_URL}
    depends_on:
