version: "3.8"

services:
  b-actix:
    build:
      context: ./
      dockerfile: .services/nginx/Dockerfile.deploy

  b-nginx:
    build:
      context: ./
      dockerfile: .services/nginx/Dockerfile.deploy
    container_name: nginx
    ports:
      - 1337:80
    networks:
      - default

networks:
  default:
    driver: bridge
