version: "3.8"

services:
  ui:
    stdin_open: true
    build:
      context: ./services/ui
      dockerfile: Dockerfile
    container_name: ui
    volumes:
      - ./services/ui:/app/ui
      - /app/ui/node_modules
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
