version: "3.8"

services:
  b-nginx:
    build:
      context: ./services
      dockerfile: ./nginx/Dockerfile.deploy
    container_name: nginx
    ports:
      - 1337:80
    networks:
      - default

networks:
  default:
    driver: bridge
