# build
FROM node:18-alpine as build-react
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV production
COPY ./services/ui/package*.json ./
RUN npm install
RUN npm install react-scripts@5.0.1
COPY ./services/ui/ .
RUN rm .eslintrc.json
RUN npm run build


# production
FROM nginx:stable-alpine as production
WORKDIR /app
COPY --from=build-react /app/build /usr/share/nginx/html
COPY ./services/nginx/default.conf /etc/nginx/conf.d/default.conf