# build
FROM node:18-alpine as build-react
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV production
COPY ./ui/package*.json ./
RUN npm install
COPY ./ui .
RUN rm .eslintrc.json
RUN npm run build


# production
FROM nginx:stable-alpine as production
WORKDIR /app
COPY --from=build-react /app/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && \
      nginx -g 'daemon off;'